language: php
php:
- 7.1
env:
  matrix:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""
  global:
      - GIT_NAME: "'Couscous auto deploy'"
      - GIT_EMAIL: d.negrier@thecodingmachine.com
      - GH_REF: github.com/thecodingmachine/tdbm
      - secure: pAdXEBkhe0KJbbZEP61lcZzvKKMkVK2RDIZTf1RzjQRgk+PxIG5JLBiHKuvG3MgtFjZbdtl2Vf6nAZbeMyy3H0eCryQCjjqdb5mS3eDekJ4WwviN6hQDc7+Xw6R1saHvDvJs9GQENUzHPWfAfY7LuwUgHXdc+BCLZmV+j0H6liZMNlXIYqP1kdwl7u5a/Y3FvXFws6R7A0giUBCb4HOYkInaXV0yzuAEsB6XBDbTjw3EqI0GBs6746O4tn7NOGaFlFSZan6RZe6jEkw7A+U3xLCfFnIN2q1uk/tk511KkOcSFQyGKRMDSKRDesdMQaOt/ze14+t+ISTqOSn8bUrCBhpj4VsjvzZE0FOS3WWGXpayODqdxuDjacwCZwiOHG7FWbwyQ3APiIrfO82ABbI8HoJURbgOb/Qnl2iPg9tCcvDqhsHxppGq5oOyhBq+GGtucOTW6lO6QnlMaez4nJJ7a3cn8WJB6NxaCZLii3aOXSLMahzFCcQxtq9/WfKwbOtf4GWUSLk28kDMov5h7tzuuHXmzOivzRxztQ9WC2GT7eMCIL8mvWFRMNiLJTE03J0ZbQDZ9N4OU3tdcgjV+d6pU6bu4SrCFtjCJnLaeLfIjoHkx+kK+kyCOQpOcuHMM6zq8l+ztd7VGZ3Br8HJTs1CxiWXrs+JIx2i8V06IE8nLKA=
before_script:
- composer update --prefer-source $PREFER_LOWEST
script:
- "./vendor/bin/phpunit"
after_script:
- "./vendor/bin/coveralls -v"
- vendor/bin/couscous travis-auto-deploy --php-version=7.1